### ISSUE TITLE
show overall download progress

### ISSUE THREAD

**Issue by veso266** [Ejz/HLSDownload#2]
Hi is it posible to show download progress (like 1%, 2%, etc) when downloading large HLS streams
and also display time remaining to finish download?
Thanks for Anwsering and Best Regards

**Comment by Ejz** [comment]
yes, it's possible, but not so quickly as it seems. will remain this issue open...

**Comment by Ejz** [comment]
use latest release [v1.3.1](https://github.com/Ejz/HLSDownload/releases/tag/v1.3.1). param `--progress` will output percents while downloading
