### ISSUE TITLE
why not support windows?

### ISSUE THREAD

**Issue by MeMadMan** [Ejz/HLSDownload#7]
//if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN')
//    _err("Windows OS is not supported!");

**Comment by Ejz** [comment]
@MeMadMan you can try to comment out this lines, but i don't guarantee it will work correctly. Anyway i'm going to review Windows support soon.

**Comment by MeMadMan** [comment]
Thanks. Not working with Xampp3.22+win7

**Comment by Ejz** [comment]
Please, describe operations you do to launch the program.
